# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033256a5466fba7c52d79a276eff95e688d3df09bbc933ba8701b689a1e787ffe711b15849674c4f1037ec1a119f56d23c47c13410c17bb2e068c0833a3906d9

test:
  secret_key_base: d9d7883f00511ea5411d95571bfdadda481643f385f49214945debf8b84dbb353309a03332ffddf044e90790ef35fa82194ab28537e3ac61918d1dcef94075c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
